// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
namespace Pure.AbpPro.BasicModule.Migrations;

[DbContext(typeof(BasicModuleHttpApiHostMigrationsDbContext))]
[Migration("20240125061400_Initial")]
partial class Initial
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.SqlServer)
            .HasAnnotation("ProductVersion", "8.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

#pragma warning restore 612, 618
    }
}
