// <auto-generated />
#nullable disable

namespace Pure.AbpPro.BasicModule.Migrations
{
    [DbContext(typeof(BasicModuleHttpApiHostMigrationsDbContext))]
    partial class BasicModuleHttpApiHostMigrationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.MySql)
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);
            
#pragma warning restore 612, 618
        }
    }
}
